---
- block:
  - name: generating integrations Compose file
    template:
      src: "{{ item }}"
      dest: "{{ docker_src }}/{{ item | basename | regex_replace('\\.j2','') }}"
    with_fileglob:
        - ../templates/tests/*.j2

  tags:
    - integration_tests
    - all_tests