---
- block:
  - name: generating Docker Compose file
    template:
      src: "{{ item }}"
      dest: "{{ docker_src }}/{{ item | basename | regex_replace('\\.j2','') }}"
    with_fileglob:
        - ../templates/orchestration/docker-compose.json.j2

  tags:
    - integration_test
    - all_tests