---
- name: running integration tests for {{ project_name }} project
  docker_service:
#    tls_hostname: "{{ docker_host }}"
    tls_verify: yes
    remove_volumes: yes
    state: absent
    files: docker-compose-integrated.yml
    project_name: "{{ project_name }}"
  tags:
    - integration_tests
